### ISSUE TITLE
Strings comparison is bad here. Don't compare objects - compare values.

### ISSUE THREAD

**Issue by fuss86** [RobRaimo/Neo4j-Wlodkowic#3]
https://github.com/RobRaimo/Neo4j-Wlodkowic/blob/df73911d6e5fb8164ee86f0d0e052f0ab53683cd/JavaJApp_JDBC_ClientGUI/src/MainFrame.java#L868

Please take a look at: 

https://stackoverflow.com/questions/513832/how-do-i-compare-strings-in-java
https://stackoverflow.com/questions/36501926/java-string-comparison-best-practice

Please fix all similar code in the source

**Comment by RobRaimo** [comment]
if ( jcbSelCreateRelation.getSelectedItem().toString().equals("ENGAGED_IN") ) {

**Comment by RobRaimo** [comment]
Or better you don't need to check ifjcbSelCreateRelation.getSelectedItem() if is null using this sysntax (Yoda Expression):
"ENGAGED_IN".equals(jcbSelCreateRelation.getSelectedItem());

**Comment by RobRaimo** [comment]
https://stackoverflow.com/questions/36501926/java-string-comparison-best-practice

**Comment by fuss86** [comment]
Good!
