### ISSUE TITLE
vrCQL doesn't have to be a "global" field - stick wth local variables

### ISSUE THREAD

**Issue by fuss86** [RobRaimo/Neo4j-Wlodkowic#6]
https://github.com/RobRaimo/Neo4j-Wlodkowic/blob/df73911d6e5fb8164ee86f0d0e052f0ab53683cd/JavaJApp_JDBC_ClientGUI/src/MainFrame.java#L22

**Comment by RobRaimo** [comment]
delete the row
22 String vrCQL = null;
and declare inside the each subclass:
String  vrCQL = "MATCH (n) RETURN n LIMIT " + jtfMatchLimitN.getText();

**Comment by RobRaimo** [comment]
Code updated for this topic on 20170914

**Comment by fuss86** [comment]
Good!
