### ISSUE TITLE
Class names should be in mixed case with the first letter of each internal word capitalized

### ISSUE THREAD

**Issue by fuss86** [RobRaimo/Neo4j-Wlodkowic#8]
https://github.com/RobRaimo/Neo4j-Wlodkowic/blob/d9c400428978cddda8e2374fc22cc84e78c18f49/JavaJApp_JDBC_ClientGUI/src/DBConnector_JDBC.java#L19

Try to stick with the Java Naming Conventions 

http://www.oracle.com/technetwork/java/codeconventions-135099.html  Classes

**Comment by RobRaimo** [comment]
Following the convention:
DBConnector_JDBC >become> DbConnectorJdbc
looking in the previous code i decide to change also one method in the MainForm class
Connection >become> tryJdbcConnection

**Comment by fuss86** [comment]
Good :)
